### ISSUE TITLE
More examples [Stacked bar chart]

### ISSUE THREAD

**Issue by emrul** [kotojs/kotojs#11]
KotoJS looks great but really lacks some examples.  We thought we'd try to fix it and would like to contribute the following example of a stacked bar chart (inspired from a pre-existing D3 chart)

http://jsbin.com/nifoxohuxa/edit?js,output

Demonstrates multiple layers, pre-draw, accessor methods and read-only config variables.

This was a learning exercise in Koto so feedback invited - especially on any missed opportunities to improve readability or maintainability.

**Comment by nicksrandall** [comment]
That looks really good! I'll add it to the readme page. Thanks!
