### ISSUE TITLE
Support D3 v4

### ISSUE THREAD

**Issue by jfsiii** [kotojs/kotojs#12]
Master currently fails with `Error: [koto] d3 js is required.` if a global `d3` isn't present. This blocks devs who don't `import d3 from "d3"` and only import any of the [many small modules](https://github.com/d3/d3/blob/master/CHANGES.md#table-of-contents) they need.

As far as I can tell, Koto only needs [d3-selection](https://github.com/d3/d3-selection/).

[d3-selection.v1.min.js](http://d3js.org/d3-selection.v1.min.js) is ~13KB (5KB gzipped) and [koto@0.3.0/dist/koto.js](https://npmcdn.com/koto@0.3.0/dist/koto.js) is ~10KB (3.5KB gzipped). Supporting d3 v4 means a user could have Koto for under 10KB gzipped.

Even if the size savings isn't compelling, it's important for Koto to support those who don't `import d3 from "d3"` in their project/page.

**Comment by jfsiii** [comment]
I'm [exploring this in a fork](https://github.com/kotojs/kotojs/compare/master...jfsiii:master)

It's only enough to get it working for my case, nowhere near PR-ready, but it gives an idea of the changes which may be required.

**Comment by nicksrandall** [comment]
I finally got around to this...
