### ISSUE TITLE
What's the distinction between .config & .accessor

### ISSUE THREAD

**Issue by jfsiii** [kotojs/kotojs#13]
Is there any guidance for when to use one vs the other? How to decide when one is or is not appropriate?

e.g.
- `chart.config('height', 500)` vs `chart.accessor('height')(500)`
- `chart.config('xScale', d3.scaleLinear)` vs `chart.accessor('xScale')(d3.scaleLinear)`

I thought it might have something to do with the API we're exposing to users, but `a` & `c` (along with `accessors` and `configs`) are exposed on the instance property (along with anything else assigned to `this` like `x` and `xAxis`) I'm don't think that's it.

**Comment by jfsiii** [comment]
Related: If I, for example, allow the user to supply an `xScale` via `config` or `accessor`, must I use it internally as `this.config('xScale')`? Is there a pattern to assign it to `this` so the code can use it as `this.xScale`?

**Comment by nicksrandall** [comment]
Configs are used to configure properties about your chart (look and feel). Accessors are used to configure how get data from the dataset you are using. The goal is to make these charts reusable across many projects. 

Here is an example:
```js
const data = [
  { date: "1/1/15", dollar: 100 },
  { date: "2/1/15", dollar: 107 },
  ...
];
const barChart = new BarChart(d3.select("#barChart"));
barChart
  .config("fill", "#99ccee")
  .accessor("date", d => d.date)
  .accessor('dollar', d => d.dollar);

barChart.draw(data);

// - OR -
const data = [
  ["1/1/15", 100],
  ["2/1/15", 105],
  ...
];
const barChart = new BarChart(d3.select("#barChart"));
barChart
  .config("fill", "steelblue")
  .accessor("date", d => d[0])
  .accessor('dollar', d => d[1]);

barChart.draw(data);
```

**Comment by jfsiii** [comment]
Thanks for the response. Perhaps my question is better phrased as, "why wouldn't everything just go in `config`"?

From what I can tell, the difference is purely for signaling intent to the user.  One could also make a config property `dateAccessor` which did the same thing and was called the same way (`this.config('dollarAccessor')(d)` vs `this.accessor('dollar')(d)`) internally.

I recognize that `accessor('colorScale')` is poor design, but AFAICT, `accessor` just saves you typing a six characters (`this.config('dollarAccessor')(d)` vs `this.accessor('dollar')(d)`). It's not as though, for example, accessors "automatically" have access to the bound data. As I showed above, the dev still must pass those values. 

Your example shows "plain" values for `config`, but what about "look and feel" items which are functions, e.g. `x` or `xScale` or if `fill` accepted a [color scale](https://github.com/d3/d3-scale#sequential-scales)? Is there any reason, other than the API presented to the user, why `colorScale` would go under `config` other than `accessor`?

Is it just a more logical place for this class of values?

I don't think issues are the best place for this question. I'd prefer Gitter but the kotojs channel seems abandoned. Feel free to close this and ping me there to discuss.
