### ISSUE TITLE
Example charts

### ISSUE THREAD

**Issue by girlwithglasses** [kotojs/kotojs#3]
Would you be able to create some sample charts / bl.ocks to demonstrate koto.js in action? It would be particularly useful to see some of the "classic" d3 charts (e.g. the bar chart from the tutorial http://mbostock.github.com/d3/tutorial/bar-2.html) re-implemented using koto.js.

**Comment by nicksrandall** [comment]
Yeah, I can do that. Great idea. Thanks @girlwithglasses

**Comment by nicksrandall** [comment]
http://bl.ocks.org/nicksrandall/53c6d59ea70afaf19cf1
